### ISSUE TITLE
Bad link on homepage for Evaluating Models > measure summarization performance

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ai-guide#19]
### Sub-section title

Evaluating-models

### Please describe your issue

https://ai-guide.future.mozilla.org/#Evaluating-models

the 4th paragraph has a link saying "measure summarization performance" which seems to take me to a disambiguation page on wikipedia: https://en.wikipedia.org/wiki/ROUGE_(metric

I think that trailing comma in the rendered page is supposed to be part of the link itself.

```diff
- https://en.wikipedia.org/wiki/ROUGE_(metric
+ https://en.wikipedia.org/wiki/ROUGE_(metric)
```

### Describe the solution you'd like to see

I need to clone the site and see if it appears anywhere else.

**Comment by skyfallsin** [comment]
resolved and queued for deploy
