### ISSUE TITLE
AI Basics: Missing word "in" 

### ISSUE THREAD

**Issue by ashandoak** [mozilla/ai-guide#20]
### Sub-section title

WHAT ARE THE PROS & CONS OF USING AN LLM?

### Please describe your issue

The word "in" is missing from the first sentence in the section. 

### Describe the solution you'd like to see

The sentence should state (missing "in" bolded for clarity):

"Although LLMs have made it possible for computers to process human language **in** ways that have been previously difficult, if not impossible, they are not without trade-offs:"

**Comment by skyfallsin** [comment]
resolved and queued for deploy
