### ISSUE TITLE
Language Models 101 - Lowercase typo in first paragraph

### ISSUE THREAD

**Issue by ashandoak** [mozilla/ai-guide#22]
### Sub-section title

WHAT'S THE DIFFERENCE BETWEEN A "LANGUAGE MODEL" AND A "LARGE LANGUAGE MODEL"?

### Please describe your issue

The third sentence of the section leads with a lowercase "usually". 

### Describe the solution you'd like to see

"usually" should be capitalized:

"Usually, a LLM provides higher quality results than smaller LMs due to its ability to capture more complex patterns in the data."

**Comment by skyfallsin** [comment]
resolved and queued for deploy
