### ISSUE TITLE
Typo: "bleeding age" instead of "bleeding edge"

### ISSUE THREAD

**Issue by mikeconley** [mozilla/ai-guide#29]
### Sub-section title

Our First Project - Summarization

### Please describe your issue

The last paragraph in the "A brief pause for context" section reads:

> However, once we have a workflow to address all of the above, you will have the means to forever be on the bleeding age of published AI research.

"bleeding age" should probably be "bleeding edge".

### Describe the solution you'd like to see

"bleeding age" should probably be "bleeding edge".

**Comment by skyfallsin** [comment]
resolved and in the queue for deployment, thank you!
